export const SELECT_VIEW = "SELECT_VIEW";
export const SELECT_ITEM = "SELECT_ITEM";
export const CREATE_ITEM = "CREATE_ITEM";
export const UPDATE_ITEMS_DATA = "UPDATE_ITEMS_DATA";
export const APPLY_FILTERS = "APPLY_FILTERS";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";

